### ISSUE TITLE
test:p_sincos Fix reference test function implementation

### ISSUE THREAD

**Issue by mateunho** [parallella/pal#119]
First of all, `p_sincos` has one input and two outputs, which is different from most functions in pal. It must have a proper test implementation.
Secondly, current (single) _reference vector_ for testing purposes hold entirely wrong values, since it's calculated using `log10f` function.
```c
#include <math.h>
#include "simple.h"

void generate_ref(float *out, size_t n)
{
    size_t i;

    for (i = 0; i < n; i++)
        out[i] = log10f(ai[i]); // copy paste mistake
}
```
Namely in [this](https://github.com/parallella/pal/blob/master/tests/math/p_sincos.c#L9) line.

**Comment by olajep** [comment]
Closing this.

@kfitch 's patch was merged in 5aa8c89f277b

// Ola
