### ISSUE TITLE
Hygene: .gitignore should ignore Autotools and libtool

### ISSUE THREAD

**Issue by indrora** [parallella/pal#124]
When you run ./bootstrap, you get a bunch of things that git should ignore, and which should be added to `.gitignore`.

**Comment by indrora** [comment]
(merged, closing)

**Comment by olajep** [comment]
Hi,

You get bonus points if you add
```
fixes #issue
```

to the commit message. Then the issue will be automagically closed when the pull is merged.

Thanks,
Ola
