### ISSUE TITLE
Should we prefer the "-lm" implementation where available?

### ISSUE THREAD

**Issue by kfitch** [parallella/pal#157]
I started by looking at sincos (and sin and cos by extension). As a result I have found that the current implementations of these functions leave a lot to be desired. These are solvable problems, but, taking a step back I think we need to answer a more fundamental question: "Is PAL the right place to be solving these problems?" Or put another way "Are we reinventing the wheel for no good reason?" If we look at the design goals for PAL we see: 
* Fast (Super fast but no "belt AND suspenders")
* Compact (Small enough to work for memory limited processors with <32KB RAM)
* Scalable (Thread and data scalable)
* Portable (Portable across different ISAs and systems)
* Permissive (Apache 2.0 license to maximize industry adoption)

I did a few tweaks to the existing "benchmark" code (which I hope to clean up and submit later) and found that for sin and cos the PAL implementations are MUCH slower (on my desktop box) than the versions in -lm
```
float psin size: 655360 duration: 000061030us
float pcos size: 655360 duration: 000100707us
float sinf size: 655360 duration: 000017791us
float cosf size: 655360 duration: 000017767us
```

Also note that the versions in the standard math library are more accurate, and (at least for the current implementation of p_sin_f32) more robust.

Also, using the standard math library should be very portable. For the level we are looking at things I don't things "scalable" or "permissive" come into play. 

The only design goal that is questionable is "compact." I would argue that on systems with limited RAM the standard math library is where a memory constrained version of things like sin and cos should live. Forcing all systems to live within the confines of some particular (although very relevant) system (like epiphany) goes against both the "portable" and "fast" design goals. Good portable code should not only work across many systems, it should also work well on those systems.

**Comment by tcptomato** [comment]
+1

**Comment by WesleyCeraso** [comment]
+1

**Comment by kfitch** [comment]
I created a branch to see what this change would look like at https://github.com/kfitch/pal/tree/uselibm

Most functions are just using the libm versions already, so the changes are not as extensive as I thought they might be. 

There are a few other functions that might also qualify:
* p_abs : This is simple enough that I think not calling the libm version is fine.
* p_absdiff : same as p_abs
* p_ln : A quick benchmark suggests the version in PAL is MUCH faster than the libm version (for me at least). I didn't check the accuracy yet though.

**Comment by kfitch** [comment]
Ooops, I forgot to mention the branch where I started work on the benchmark improvements: https://github.com/kfitch/pal/tree/benchmark

Also, I  would be curious to hear the opinion of @westonized on this topic.

**Comment by aolofsson** [comment]
@kfitch 

-Code size is a big deal. This is one of the reasons why traditional embedded archs have always had their own libs (TI, ADI, Microchip, etc).

-There is no reason for the performance of this lib to be worse than libm. It should be much better. If it's worse than we have failed!

-libm running on a scalar is a nightmare to make fast. No vectorization and lots of pipeline stalls. Vectorizing gives the compiler freedom, thus better performance. 

-Yes, we are reinventing the wheel, but because I don't see another choice. First thought was to simply take the newlib implementation, cut out the fat and vectorize. This is why I included the old SUN lib inside the repo:
https://github.com/parallella/pal/tree/master/src/math/msun/src

**Comment by westonized** [comment]
@aolofsson 

>There is no reason for the performance of this lib to be worse than libm. It should be much better.

I thought I read, and now can't find it, that we were aiming for 40% performance of whatever native method you have available to test against on whatever architecture. I took that to mean if native can process 10 in a given time, you need to process at least 4.

Or is it that the better performance you talk of only kicks in once we are processing a whole vector?

**Comment by aolofsson** [comment]
40% only applicable for vectors
