### ISSUE TITLE
image: Fix inconsistencies between header/implementation

### ISSUE THREAD

**Issue by mateunho** [parallella/pal#16]
Refactoring include:
- `32f` to `f32` suffix change
- argument re-ordering
- correction of mistyped function name

**Comment by olajep** [comment]
Should be fixed here?
https://github.com/parallella/pal/commit/33fd816c0b068dc47be8f002d006de81a730807a

// Ola

**Comment by mateunho** [comment]
Fixed what I've wanted to be fixed :+1: 
... couple minutes of typing issue in vain :cry:
