### ISSUE TITLE
e_coreid.h and e_common.h

### ISSUE THREAD

**Issue by ghost** [parallella/pal#165]
Some files in pal library will not compile because headers are missing.
The source code file:
 e_coreid_config.c
 located in:
 src/base/epiphany/
is listing and referring to two header files:
e_coreid.h
e_common.h
These two headers are missing in the library.

**Comment by Adams-Ben** [comment]
these headers were found at:
./opt/adapteva/esdk.2015.1/tools/e-gnu.armv7l/epiphany-elf/include/e_coreid.h

After linking these headers and rebuilding another error occur:

||=== Build: Debug in MyProject1 (compiler: GNU GCC Compiler) ===|
/tmp/ccwMmFam.s|41|Error: bad instruction `movfs r0,COREID'|
||=== Build failed: 1 error(s), 0 warning(s) (0 minute(s), 1 second(s)) ===|

**Comment by olajep** [comment]
I don't see how this is applicable. Those files are not in the build at all. Importing the pal sources directly into eclipse(?) won't work. You first build and install pal and then link with -lpal in your project.

Can we close this?

Thanks,
Ola

**Comment by Adamszk** [comment]
Yes we can close this issue.
