### ISSUE TITLE
Assertions

### ISSUE THREAD

**Issue by eliteraspberries** [parallella/pal#178]
Hi,

In PR #73 it was agreed that there should be no error checking, in favour of small code size.

I agree, but I would like to propose a compromise: that assertions be included in the code, and that the PAL library be compiled with `NDEBUG` defined or not depending on whether the build is for testing or production.

With `NDEBUG` defined at compile time, an assertion becomes a nop:

> Forcing a definition of the name NDEBUG, either from the compiler command line or with the preprocessor control statement #define NDEBUG ahead of the #include \<assert.h\> statement, shall stop assertions from being compiled into the program.

I really like assertions because they help document the code, better than comments in my opinion.

Please let me know what you think.

**Comment by aolofsson** [comment]
Sounds reasonable! Can you verify that this method works reasonably well on all three current archs (ARM, x86, Epiphany).

For example, we know that the -O0 level in the Epiphany is REALLY not optimized, so the code might become quite large. For this to be useful in small platforms, the delta between optimized code and debug code cannot be too large. (ie 10x). Depending on what libs get pulled in the factor has been 10x in some cases.

An example showing how you would use this would be helpful.

**Comment by eliteraspberries** [comment]
You're right, -O2 is a more reasonable default. I changed it in 0f879bd.

I'm only developing on x86 and ARM for now. I don't actually have a Parallella yet but I'm hoping to soon. I understand that assertions are a preference (I really like them) but theoretically they should help avoid bugs by making things "fail fast." When actually using the library, I think a good use would be to run your program with "typical" inputs using a debug build, then if it works well, to switch to the optimized build.
