### ISSUE TITLE
p_function_f32.dat has a memory

### ISSUE THREAD

**Issue by Adamszk** [parallella/pal#204]
Note:
Case 1) Clean pal1.
 bootstrap/configure/make/make check. 
pal1 becomes pal2
When I run a test with a function1 and with file1.dat, I get a failure.  Thats okay.
When I run a test with a function1 and with file2.dat, I get a failure.  Thats okay.
now pal2 is old.

Case 2) Clean pal1. same as before but  in different directory. 
bootstrap/configure/make/make check. pal1 becomes pal2
When I run a test with a function1 and with file2.dat. I get a pass.   Thats  NOT OKAY.

Case 1 and 2 uses the same clean pal (the same date etc)

Observation,
Even when I remove file2.dat.gold.h case 1 still remembers and uses the same dat results from memory. file.dat has a memory.
How do I flush or clean pal properly so that I do not have reinstall pal for secondary test.?

**Comment by eliteraspberries** [comment]
The unit tests use the "gold" data. The gold is a header file `.gold.h` generated from a `.dat` file. For example the file `p_erf_f32.gold.h` in tests/math/gold/ is generated from the file `p_erf_f32.dat`.

If you modify the `.dat` file, delete the `.gold.h` file, and continue with `make`.

**Comment by eliteraspberries** [comment]
This is what I do: `find tests -name '*.gold.h' | xargs rm`

**Comment by Adamszk** [comment]
Okay.Thanks
