### ISSUE TITLE
word alignment errors during init of epiphany

### ISSUE THREAD

**Issue by peteasa** [parallella/pal#227]
@olajep I have built with some success the pal libraries on the target and run some simple tests.  So far not been able to get device/epiphany working.  https://github.com/parallella/pal/blob/master/src/base/devices/posix/epiphany/loader.c#L278 give an alignment error fixed with 
`
reg_write(core,` i << 2, MMR_R0 + (i << 2));
`
reworked some of the examples and runtest.epiphany.c but still cant get epiphany code to load.  p_load() returns -2.  any suggestions?

Peter.

**Comment by peteasa** [comment]
Ok so drilling down a bit into this.  the tests try to map memory for status and results and this api call is failing.. I am guessing that the changes to the kernel make p_map unsupported on Epiphany so I am now looking for an alternative way to map memory with something like e_shm_alloc() perhaps the pal equivalent has not yet been implemented?

**Comment by olajep** [comment]
> reg_write(core, i << 2, MMR_R0 + (i << 2));

Thank you, don't know what I was thinking there, I think it should be this though ?
``` 
reg_write(core, MMR_R0, (i << 2));
```

right now the posix host --> epiphany device code only works with the simulator
I'll fix the native device code as soon as I can but it won't be for another week or two.
Patches always welcome of course ;)


If you want to hack on it you'll  likely find all bugs in src/base/devices/posix/epiphany/device.c

It might be enough to fix dev_map(), dev_map_raw(), and provide a mem_ops structure,
see simulator.c for how it's implemented there.


Cheers,
Ola

**Comment by peteasa** [comment]
@olajep I have created a pull request to fix this and make my version of the epiphany test work.  I will do a bit more later and modify runtest.epiphany.c.  My test version worked with this code and got a response from the epiphany core so I think that the changes are good.
