### ISSUE TITLE
math: Add defines for max and min values in header

### ISSUE THREAD

**Issue by mateunho** [parallella/pal#26]
> Linked with #24 and #25

**Comment by mateunho** [comment]
Ok, since previous issues were handled, this might be deprecated, but...
Header defines for MAXFLOAT or INFINITY, or NAN can be useful (see [OpenCL](https://www.khronos.org/files/opencl20-quick-reference-card.pdf)).

So, for now, I'll leave it open.

**Comment by aolofsson** [comment]
Added to include, closing issue
