### ISSUE TITLE
please help: unclear interface of p_sad8x8_f32, p_sad16x16_f32

### ISSUE THREAD

**Issue by alibabashack** [parallella/pal#59]
Hi, I would like to implement the mentioned functions, but the description of the arguments is unclear to me. My guess (for the 8x8 case; for 16x16 analog):

SAD works on an input _source_ image x with dimensions rows x cols. There is a second _reference_ image with the same dimensions as x. m is a pointer to the upper left corner of a 8x8 block within this second image. (Therefore m is *not* an 8x8 array.) The result vector r is a 2D array with dimensions (rows - 7) x (cols - 7) holding the absolute differences for the possible offsets of the 8x8 block within the _source_ image.

Please tell me if these assumptions are correct. Thank you.
Greetings, Alexander

**Comment by aolofsson** [comment]
You are right, the interface made no sense. I have updated the file, should make more sense now.  Function returns a scalar.

**Comment by alibabashack** [comment]
Thank you, for clarification. The pseudo code did it.
