### ISSUE TITLE
Improve const-correctness

### ISSUE THREAD

**Issue by elfring** [parallella/pal#66]
I suggest to add the key word "const" to the type specifiers for parameters like the following.
* x (function "[p_conv2d_f32](https://github.com/parallella/pal/blob/313b73c1cbd624bf8b0939842c45b1e8e635c643/include/pal_image.h#L3)")
* a (function "[p_itof](https://github.com/parallella/pal/blob/60e052ee2f797398f92c8d672c6c1689da226045/include/pal_math.h#L88)")

Would you like to apply the advices from [an article](https://en.wikipedia.org/w/index.php?title=Const_%28computer_programming%29#Consequences "const-correctness") to more places in your source files?

**Comment by olajep** [comment]
Yes, that's a good idea. Such patches will be accepted.

Thanks, Ola

**Comment by mateunho** [comment]
Resolved with #78, to be closed.

**Comment by elfring** [comment]
Thanks for [your source code improvement](https://github.com/GBuella/pal/commit/d445189b56d4a2aa2cf6cf37d8f0db2dd94bc16a "Better const-correctness").
