### ISSUE TITLE
Use of angle brackets around file names for include statements

### ISSUE THREAD

**Issue by elfring** [parallella/pal#67]
Would you like to [replace any double quotes](https://github.com/parallella/pal/blob/33fd816c0b068dc47be8f002d006de81a730807a/include/pal.h#L3 "Check header file inclusion style") by [angle brackets around file names for include statements](http://stackoverflow.com/questions/21593/what-is-the-difference-between-include-filename-and-include-filename "What is the difference between #include <filename> and #include “filename”?")?

**Comment by olajep** [comment]
That depends. The double quotes in 'pal.h' are intended. In this case we want pal.h to include files in the same directory so we know the user ends up with headers from the same version of pal.

If you see something else that looks strange please open a new issue.

Closing this.

Thanks,
Ola

**Comment by elfring** [comment]
I suggest to reconsider the consequences of [the following wording](http://c0x.coding-guidelines.com/6.10.2.html "Source file inclusion") from [the section "16.2 Source file inclusion"](http://open-std.org/jtc1/sc22/wg21/docs/papers/2013/n3797.pdf "C++ working draft") in the standard specification for the programming language "C++".
```
…
The named source file is searched for in an implementation-defined manner. If this search is not supported, or if the search fails, the directive is reprocessed as if it read

#include <h-char-sequence> new-line
…
```

* How do you think about to avoid "a duplicated file search" here?
* Would you like to [restrict the searched directories](https://gcc.gnu.org/onlinedocs/cpp/Include-Syntax.html "Include syntax description") for header files of your software?

**Comment by olajep** [comment]
Hi,

At least gcc, g++, clang, and clang++ behave in a sane way (look for files relative to header file first before searching in directories provided by -I directive). Please let us know if you find a compiler you think we should support that does behave this way. Then we might have to reconsider.

Thanks,
Ola

**Comment by elfring** [comment]
There are different opinions about the handling of the involved implementation-defined behaviour.
* I would generally prefer to exclude the potential for the inclusion of header files from unexpected directories. Can such a security detail become a bit more important?
* Is there a speed difference measurable if a file is not found outside the specified include directories and the search will be retried with "the angle brackets inclusion method"?
